spring.application.name=backend
spring.security.user.name=none
spring.security.user.password=none
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

#MySql
spring.datasource.url=jdbc:mysql://localhost:3306/cinevo?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#logging.level.org.hibernate.type.descriptor.sql=TRACE

#TMDB
api.url=https://api.themoviedb.org/3/
api.key=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyYTVmNjY3NWZiZTE1NTAyYmVjMzc1ZTU5ZmQ4OTA3ZSIsIm5iZiI6MTc1NjM1ODMxNS4zNzYsInN1YiI6IjY4YWZlNmFiZGUzZjM1ODIzODYyNGU4NSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.5udfIWArAtyIGUtj15hAfwEmu6I-1fOMS2lV67mc4F8
